arrival:
  TASK_1:  # the arrival process for tasks of type 1 (exponential with rate 6 tasks/sec)
    distribution: "EXPONENTIAL"
    parameters:
      r: 4.00
  TASK_2:  # the arrival process for tasks of type 2 (exponential with rate 6.25 tasks/sec)
    distribution: "EXPONENTIAL"
    parameters:
      r: 6.25

system:
  cloudlet:
    n_servers: 20  # the number of servers
    server_selection: "RANDOM"  # the server-selection rule
    controller_algorithm: "ALGORITHM_1"  # the controller algorithm
    service:
      TASK_1:  # the service process for tasks of type 1 (exponential with rate 0.45 tasks/sec)
        distribution: "EXPONENTIAL"
        parameters:
          r: 0.45
      TASK_2:  # the service process for tasks of type 2 (exponential with rate 0.27 tasks/sec)
        distribution: "EXPONENTIAL"
        parameters:
          r: 0.27
  cloud:
      service:
        TASK_1:  # the service process for tasks of type 1 (exponential with rate 0.25 tasks/sec)
          distribution: "EXPONENTIAL"
          parameters:
            r: 0.25
        TASK_2:  # the service process for tasks of type 2 (exponential with rate 0.22 tasks/sec)
          distribution: "EXPONENTIAL"
          parameters:
            r: 0.22
      setup:
        TASK_1:  # the service process for tasks of type 1 (deterministic with value 0 sec)
          distribution: "DETERMINISTIC"
          parameters:
            v: 0
        TASK_2:  # the service process for tasks of type 2 (exponential with mean 0.8 sec)
          distribution: "EXPONENTIAL"
          parameters:
            m: 0.8